import { Link } from '@inertiajs/react';
import PublicLayout from '../Layouts/PublicLayout';
import { usePublicTranslation, usePublicLocale } from '../usePublicTranslation';

type DocumentItem = { slug: string; title: string; description: string | null; category: string; published_at: string | null; reference_date: string | null; download_count: number };
const RESOURCE_LINKS = ['Constitution of Zimbabwe', 'Local Government Laws Amendment Act', 'Rural Land Act', 'Stock Theft Prevention Act', 'Traditional Leaders Act', 'Mutoko Master Plan — public exhibition notice'];
export default function Documents({ documents, categories, years, filters }: { documents: DocumentItem[]; categories: string[]; years: number[]; filters: { category: string | null; year: string | null; department: string | null; q: string } }) {
    const t = usePublicTranslation();
    const locale = usePublicLocale();
    return <PublicLayout><div className="mx-auto max-w-5xl px-6 py-12"><h1 className="text-3xl font-bold">{t('councilDocuments')}</h1><p className="mt-4">Council plans, budgets, minutes and statutory instruments. Key references include the Constitution, local government and land legislation, and the Mutoko Master Plan currently on public exhibition for comment at Stand 366 Mutoko Centre.</p><section aria-label="Key resources" className="mt-6"><h2 className="font-semibold">Key resources</h2><ul className="list-disc pl-6">{RESOURCE_LINKS.map(r => <li key={r}>{r}</li>)}</ul></section><form method="get" action={`/${locale}/documents`} className="mt-6 flex flex-wrap gap-4"><label>{t('keyword')}<input type="search" name="q" defaultValue={filters.q} maxLength={100} /></label><label>{t('category')}<select name="category" defaultValue={filters.category ?? ''}><option value="">{t('clearFilters')}</option>{categories.map(category => <option key={category} value={category}>{category}</option>)}</select></label><label>{t('year')}<select name="year" defaultValue={filters.year ?? ''}><option value="">{t('clearFilters')}</option>{years.map(year => <option key={year} value={year}>{year}</option>)}</select></label><button type="submit">{t('filter')}</button></form>{documents.length === 0 ? <p className="mt-6">{t('noDocuments')}</p> : <ul className="mt-6 space-y-6">{documents.map(document => <li key={document.slug}><Link href={`/${locale}/documents/${document.slug}`} className="font-semibold underline">{document.title}</Link><p>{document.description}</p><small>{document.category}{document.reference_date ? ` — ${t('referenceYear')}: ${document.reference_date.slice(0, 4)}` : ''} — {document.download_count} {t('downloadCount')}</small></li>)}</ul>}</div></PublicLayout>;
}
