import { Link } from '@inertiajs/react';
import PublicLayout from '../Layouts/PublicLayout';
import { usePublicTranslation } from '../usePublicTranslation';

type DocumentItem = { slug: string; title: string; description: string | null; category: string; published_at: string | null; reference_date: string | null; download_count: number };
export default function Documents({ documents, categories, years, filters }: { documents: DocumentItem[]; categories: string[]; years: number[]; filters: { category: string | null; year: string | null; department: string | null; q: string } }) {
    const t = usePublicTranslation();
    return <PublicLayout><div className="mx-auto max-w-5xl px-6 py-12"><h1 className="text-3xl font-bold">Council documents</h1><form method="get" action="/documents" className="mt-6 flex flex-wrap gap-4"><label>{t('keyword')}<input type="search" name="q" defaultValue={filters.q} maxLength={100} /></label><label>{t('category')}<select name="category" defaultValue={filters.category ?? ''}><option value="">{t('clearFilters')}</option>{categories.map(category => <option key={category} value={category}>{category}</option>)}</select></label><label>{t('year')}<select name="year" defaultValue={filters.year ?? ''}><option value="">{t('clearFilters')}</option>{years.map(year => <option key={year} value={year}>{year}</option>)}</select></label><button type="submit">{t('filter')}</button></form>{documents.length === 0 ? <p className="mt-6">{t('noDocuments')}</p> : <ul className="mt-6 space-y-6">{documents.map(document => <li key={document.slug}><Link href={`/documents/${document.slug}`} className="font-semibold underline">{document.title}</Link><p>{document.description}</p><small>{document.category}{document.reference_date ? ` — ${t('referenceYear')}: ${document.reference_date.slice(0, 4)}` : ''} — {document.download_count} {t('downloadCount')}</small></li>)}</ul>}</div></PublicLayout>;
}
