import { Link } from '@inertiajs/react';
import PublicLayout from '../Layouts/PublicLayout';
import { usePublicTranslation } from '../usePublicTranslation';
type Ward = { slug: string; name: string };
type LinkedDocument = { slug: string; title: string };
type Update = { update_date: string | null; title: string; summary: string | null; progress_percent: number | null };
type ProjectDetail = { slug: string; title: string; project_type: string; location: string | null; summary: string | null; description: string; starts_at: string | null; expected_completed_at: string | null; completed_at: string | null; project_status: string; progress_percent: number | null; contact_instructions: string | null; image_url: string | null };
const projectStatuses: Record<string, string> = { planned: 'planned', ongoing: 'ongoing', completed: 'completed', on_hold: 'onHold', cancelled: 'cancelled' };
export default function Project({ project, department, wards, documents, updates }: { project: ProjectDetail; department: string | null; wards: Ward[]; documents: LinkedDocument[]; updates: Update[] }) {
    const t = usePublicTranslation();
    return <PublicLayout><div className="container coming-soon"><p><Link href="/projects">{t('projects')}</Link></p><h1>{project.title}</h1><p>{project.project_type === 'programme' ? t('programme') : t('project')} — {t('projectStatus')}: {t(projectStatuses[project.project_status] as 'planned')}</p>{project.location && <p>{t('location')}: {project.location}</p>}{project.summary && <p>{project.summary}</p>}{project.image_url && <img src={project.image_url} alt={project.title} />}{department && <p>{t('department')}: {department}</p>}{wards.length > 0 && <p>{t('wards')}: {wards.map(ward => ward.name).join(', ')}</p>}<section><h2>{t('timeline')}</h2><p>{t('startsAt')}: {project.starts_at ?? '—'} — {t('expectedCompletion')}: {project.expected_completed_at ?? '—'}{project.completed_at ? ` — ${t('completedAt')}: ${project.completed_at}` : ''}</p>{project.progress_percent !== null && <p>{t('progress')}: {project.progress_percent}%</p>}</section><p>{project.description}</p>{project.contact_instructions && <section><h2>{t('contactCouncil')}</h2><p>{project.contact_instructions}</p></section>}<section><h2>{t('projectUpdates')}</h2>{updates.length === 0 ? <p>{t('noProjectUpdates')}</p> : <ul>{updates.map((update, index) => <li key={index}><strong>{update.title}</strong> ({update.update_date}){update.summary && <p>{update.summary}</p>}{update.progress_percent !== null && <p>{t('progress')}: {update.progress_percent}%</p>}</li>)}</ul>}</section>{documents.length > 0 && <section><h2>{t('relatedDocuments')}</h2><ul>{documents.map(document => <li key={document.slug}><Link href={`/documents/${document.slug}`}>{document.title}</Link></li>)}</ul></section>}<p><Link href="/contact">{t('contactCouncil')}</Link></p></div></PublicLayout>;
}
