import { Link } from '@inertiajs/react';
import PublicLayout from '../Layouts/PublicLayout';
import { usePublicTranslation, usePublicLocale } from '../usePublicTranslation';
type Project = { slug: string; title: string; project_type: string; project_status: string; location: string | null; summary: string | null; progress_percent: number | null };
const projectStatuses: Record<string, string> = { planned: 'planned', ongoing: 'ongoing', completed: 'completed', on_hold: 'onHold', cancelled: 'cancelled' };
export default function Projects({ projects, filters }: { projects: Project[]; filters: { status: string | null; type: string | null; department: string | null; ward: string | null } }) {
    const t = usePublicTranslation();
    const locale = usePublicLocale();
    return <PublicLayout><div className="container coming-soon"><h1>{t('projects')}</h1><p>{t('projectsDesc')}</p><form method="get" action="/projects"><label htmlFor="projects-status">{t('projectStatus')}</label><select id="projects-status" name="status" defaultValue={filters.status ?? ''}><option value="">{t('clearFilters')}</option><option value="planned">{t('planned')}</option><option value="ongoing">{t('ongoing')}</option><option value="completed">{t('completed')}</option><option value="on_hold">{t('onHold')}</option><option value="cancelled">{t('cancelled')}</option></select><label htmlFor="projects-type">{t('projectType')}</label><select id="projects-type" name="type" defaultValue={filters.type ?? ''}><option value="">{t('clearFilters')}</option><option value="project">{t('project')}</option><option value="programme">{t('programme')}</option></select><button type="submit">{t('filter')}</button></form>{projects.length === 0 ? <p>{t('noProjects')}</p> : <ul>{projects.map(project => <li key={project.slug}><Link href={`/${locale}/projects/${project.slug}`}>{project.title}</Link><p>{t(projectStatuses[project.project_status] as 'planned')}{project.location ? ` — ${project.location}` : ''}{project.progress_percent !== null ? ` — ${project.progress_percent}%` : ''}</p>{project.summary && <p>{project.summary}</p>}</li>)}</ul>}</div></PublicLayout>;
}
