import { Link } from '@inertiajs/react';
import PublicLayout from '../Layouts/PublicLayout';
import { usePublicLocale, usePublicTranslation } from '../usePublicTranslation';
type Profile = { public_name: string | null; public_summary: string | null; public_description: string | null; responsibilities: string[] | null };
type Head = { slug: string; name: string; title: string } | null;
type OfficialItem = { slug: string; name: string; title: string };
type ServiceItem = { slug: string; name: string; summary: string | null };
type ContactItem = { office: string; type: string; value: string };
type DocumentItem = { slug: string; title: string; category: string };
type EditorialItem = { slug: string; title: string };
export default function PublicDepartment({ department, head, officials = [], services = [], contacts = [], documents = [], news = [], notices = [] }: { department: Profile; head: Head; officials?: OfficialItem[]; services?: ServiceItem[]; contacts?: ContactItem[]; documents?: DocumentItem[]; news?: EditorialItem[]; notices?: EditorialItem[] }) {
    const locale = usePublicLocale();
    const t = usePublicTranslation();
    return <PublicLayout><div className="container coming-soon"><h1>{department.public_name}</h1>{department.public_summary && <p>{department.public_summary}</p>}{department.public_description && <p>{department.public_description}</p>}{department.responsibilities?.length ? <section><h2>{t('responsibilities')}</h2><ul>{department.responsibilities.map((item, index) => <li key={index}>{item}</li>)}</ul></section> : null}{head && <section><h2>{t('headOfDepartment')}</h2><p><Link href={`/${locale}/officials/${head.slug}`}>{head.name}</Link> — {head.title}</p></section>}{officials.length > 0 && <section><h2>{t('officials')}</h2><ul>{officials.map(official => <li key={official.slug}><Link href={`/${locale}/officials/${official.slug}`}>{official.name}</Link> — {official.title}</li>)}</ul></section>}{services.length > 0 && <section><h2>{t('services')}</h2><ul>{services.map(service => <li key={service.slug}><Link href={`/${locale}/services/${service.slug}`}>{service.name}</Link>{service.summary && <p>{service.summary}</p>}</li>)}</ul></section>}{contacts.length > 0 && <section><h2>{t('departmentContacts')}</h2><ul>{contacts.map((contact, index) => <li key={`${contact.office}-${index}`}><strong>{contact.office}:</strong> {contact.value}</li>)}</ul></section>}{documents.length > 0 && <section><h2>{t('documents')}</h2><ul>{documents.map(document => <li key={document.slug}><Link href={`/${locale}/documents/${document.slug}`}>{document.title}</Link> — {document.category}</li>)}</ul></section>}{(news.length > 0 || notices.length > 0) && <section><h2>News and notices</h2><ul>{news.map(item => <li key={`news-${item.slug}`}><Link href={`/${locale}/news/${item.slug}`}>{item.title}</Link></li>)}{notices.map(item => <li key={`notice-${item.slug}`}><Link href={`/${locale}/notices/${item.slug}`}>{item.title}</Link></li>)}</ul></section>}<p><Link href={`/${locale}/contact`}>Contact this department</Link></p></div></PublicLayout>;
}
